### ISSUE TITLE
Need to be able to update some objects when route changes to new route key

### ISSUE THREAD

**Issue by bryanrasmussen** [youseedk/reflux-routing#8]
Assuming I have some routes

Routing.define('Address', '/Address/:id/:subject/:state', {
    subject: {required: false},
    state: {required: false}
});

Routing.define('Customer', '/Customer/:id/:subject/:state', {
    subject: {required: false},
    state: {required: false}
});

Routing.define('AMSCustomer', '/AMSCustomer/:id/:amsNumber/:subject/:state', {
    subject: {required: false},
    state: {required: false}
});

Routing.define('LightboxLoaded', '/LightboxLoaded/:isLoaded');

When my route changes from !/LighboxLoaded/true to /Address/someIDHERE then the value of the LightboxLoaded object in the state should be either null, undefined or something that allows me to know that we are no longer in a lightboxloaded route.

**Comment by christianbak** [comment]
The trick here is to use the same key for the different routes.
There is a new fix that will let you define multiple routes with the same key. That will give you exactly the behaviour you're asking for.
